version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
    - goimports
