// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package api

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
	"github.com/massdriver-cloud/mcp-server/internal/api/scalars"
)

// Input for creating a new environment.
type CreateEnvironmentInput struct {
	// Unique identifier within the project, max 20 lowercase alphanumeric characters. Cannot be changed after creation.
	Id string `json:"id"`
	// Human-readable name shown in the UI
	Name string `json:"name"`
	// Optional details about this environment
	Description string `json:"description"`
}

// GetId returns CreateEnvironmentInput.Id, and is useful for accessing the field via an interface.
func (v *CreateEnvironmentInput) GetId() string { return v.Id }

// GetName returns CreateEnvironmentInput.Name, and is useful for accessing the field via an interface.
func (v *CreateEnvironmentInput) GetName() string { return v.Name }

// GetDescription returns CreateEnvironmentInput.Description, and is useful for accessing the field via an interface.
func (v *CreateEnvironmentInput) GetDescription() string { return v.Description }

type CreateProjectInput struct {
	// Unique identifier, max 12 lowercase alphanumeric characters. Cannot be changed after creation.
	Id string `json:"id"`
	// Human-readable name shown in the UI
	Name string `json:"name"`
	// Optional details about what this project contains
	Description string `json:"description"`
}

// GetId returns CreateProjectInput.Id, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetId() string { return v.Id }

// GetName returns CreateProjectInput.Name, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetName() string { return v.Name }

// GetDescription returns CreateProjectInput.Description, and is useful for accessing the field via an interface.
func (v *CreateProjectInput) GetDescription() string { return v.Description }

// Filter criteria for listing environments.
type EnvironmentsFilter struct {
	// Filter to environments in specific project(s)
	ProjectIds []string `json:"projectIds"`
	// Filter by environment ID (the local identifier, e.g., 'staging'). Matches what was provided when creating the environment.
	Ids []string `json:"ids"`
}

// GetProjectIds returns EnvironmentsFilter.ProjectIds, and is useful for accessing the field via an interface.
func (v *EnvironmentsFilter) GetProjectIds() []string { return v.ProjectIds }

// GetIds returns EnvironmentsFilter.Ids, and is useful for accessing the field via an interface.
func (v *EnvironmentsFilter) GetIds() []string { return v.Ids }

// Input for updating an environment.
type UpdateEnvironmentInput struct {
	// Human-readable name shown in the UI
	Name string `json:"name"`
	// Optional details about this environment
	Description string `json:"description"`
}

// GetName returns UpdateEnvironmentInput.Name, and is useful for accessing the field via an interface.
func (v *UpdateEnvironmentInput) GetName() string { return v.Name }

// GetDescription returns UpdateEnvironmentInput.Description, and is useful for accessing the field via an interface.
func (v *UpdateEnvironmentInput) GetDescription() string { return v.Description }

type UpdateProjectInput struct {
	// Human-readable name shown in the UI
	Name string `json:"name"`
	// Optional details about what this project contains
	Description string `json:"description"`
}

// GetName returns UpdateProjectInput.Name, and is useful for accessing the field via an interface.
func (v *UpdateProjectInput) GetName() string { return v.Name }

// GetDescription returns UpdateProjectInput.Description, and is useful for accessing the field via an interface.
func (v *UpdateProjectInput) GetDescription() string { return v.Description }

// __createEnvironmentInput is used internally by genqlient
type __createEnvironmentInput struct {
	Organization string                 `json:"organization"`
	Project      string                 `json:"project"`
	Input        CreateEnvironmentInput `json:"input"`
}

// GetOrganization returns __createEnvironmentInput.Organization, and is useful for accessing the field via an interface.
func (v *__createEnvironmentInput) GetOrganization() string { return v.Organization }

// GetProject returns __createEnvironmentInput.Project, and is useful for accessing the field via an interface.
func (v *__createEnvironmentInput) GetProject() string { return v.Project }

// GetInput returns __createEnvironmentInput.Input, and is useful for accessing the field via an interface.
func (v *__createEnvironmentInput) GetInput() CreateEnvironmentInput { return v.Input }

// __createProjectInput is used internally by genqlient
type __createProjectInput struct {
	Organization string             `json:"organization"`
	Input        CreateProjectInput `json:"input"`
}

// GetOrganization returns __createProjectInput.Organization, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetOrganization() string { return v.Organization }

// GetInput returns __createProjectInput.Input, and is useful for accessing the field via an interface.
func (v *__createProjectInput) GetInput() CreateProjectInput { return v.Input }

// __deleteEnvironmentInput is used internally by genqlient
type __deleteEnvironmentInput struct {
	Organization string `json:"organization"`
	Id           string `json:"id"`
}

// GetOrganization returns __deleteEnvironmentInput.Organization, and is useful for accessing the field via an interface.
func (v *__deleteEnvironmentInput) GetOrganization() string { return v.Organization }

// GetId returns __deleteEnvironmentInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteEnvironmentInput) GetId() string { return v.Id }

// __deleteProjectInput is used internally by genqlient
type __deleteProjectInput struct {
	Organization string `json:"organization"`
	Id           string `json:"id"`
}

// GetOrganization returns __deleteProjectInput.Organization, and is useful for accessing the field via an interface.
func (v *__deleteProjectInput) GetOrganization() string { return v.Organization }

// GetId returns __deleteProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteProjectInput) GetId() string { return v.Id }

// __getEnvironmentInput is used internally by genqlient
type __getEnvironmentInput struct {
	Organization string `json:"organization"`
	Id           string `json:"id"`
}

// GetOrganization returns __getEnvironmentInput.Organization, and is useful for accessing the field via an interface.
func (v *__getEnvironmentInput) GetOrganization() string { return v.Organization }

// GetId returns __getEnvironmentInput.Id, and is useful for accessing the field via an interface.
func (v *__getEnvironmentInput) GetId() string { return v.Id }

// __getProjectInput is used internally by genqlient
type __getProjectInput struct {
	Organization string `json:"organization"`
	Id           string `json:"id"`
}

// GetOrganization returns __getProjectInput.Organization, and is useful for accessing the field via an interface.
func (v *__getProjectInput) GetOrganization() string { return v.Organization }

// GetId returns __getProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__getProjectInput) GetId() string { return v.Id }

// __listEnvironmentsInput is used internally by genqlient
type __listEnvironmentsInput struct {
	Organization string             `json:"organization"`
	Filter       EnvironmentsFilter `json:"filter"`
	Cursor       scalars.Cursor     `json:"cursor"`
}

// GetOrganization returns __listEnvironmentsInput.Organization, and is useful for accessing the field via an interface.
func (v *__listEnvironmentsInput) GetOrganization() string { return v.Organization }

// GetFilter returns __listEnvironmentsInput.Filter, and is useful for accessing the field via an interface.
func (v *__listEnvironmentsInput) GetFilter() EnvironmentsFilter { return v.Filter }

// GetCursor returns __listEnvironmentsInput.Cursor, and is useful for accessing the field via an interface.
func (v *__listEnvironmentsInput) GetCursor() scalars.Cursor { return v.Cursor }

// __listProjectsInput is used internally by genqlient
type __listProjectsInput struct {
	Organization string         `json:"organization"`
	Cursor       scalars.Cursor `json:"cursor"`
}

// GetOrganization returns __listProjectsInput.Organization, and is useful for accessing the field via an interface.
func (v *__listProjectsInput) GetOrganization() string { return v.Organization }

// GetCursor returns __listProjectsInput.Cursor, and is useful for accessing the field via an interface.
func (v *__listProjectsInput) GetCursor() scalars.Cursor { return v.Cursor }

// __updateEnvironmentInput is used internally by genqlient
type __updateEnvironmentInput struct {
	Organization string                 `json:"organization"`
	Id           string                 `json:"id"`
	Input        UpdateEnvironmentInput `json:"input"`
}

// GetOrganization returns __updateEnvironmentInput.Organization, and is useful for accessing the field via an interface.
func (v *__updateEnvironmentInput) GetOrganization() string { return v.Organization }

// GetId returns __updateEnvironmentInput.Id, and is useful for accessing the field via an interface.
func (v *__updateEnvironmentInput) GetId() string { return v.Id }

// GetInput returns __updateEnvironmentInput.Input, and is useful for accessing the field via an interface.
func (v *__updateEnvironmentInput) GetInput() UpdateEnvironmentInput { return v.Input }

// __updateProjectInput is used internally by genqlient
type __updateProjectInput struct {
	Organization string             `json:"organization"`
	Id           string             `json:"id"`
	Input        UpdateProjectInput `json:"input"`
}

// GetOrganization returns __updateProjectInput.Organization, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetOrganization() string { return v.Organization }

// GetId returns __updateProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetId() string { return v.Id }

// GetInput returns __updateProjectInput.Input, and is useful for accessing the field via an interface.
func (v *__updateProjectInput) GetInput() UpdateProjectInput { return v.Input }

// createEnvironmentCreateEnvironmentEnvironmentPayload includes the requested fields of the GraphQL type EnvironmentPayload.
type createEnvironmentCreateEnvironmentEnvironmentPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage `json:"messages"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment `json:"result"`
}

// GetSuccessful returns createEnvironmentCreateEnvironmentEnvironmentPayload.Successful, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns createEnvironmentCreateEnvironmentEnvironmentPayload.Messages, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayload) GetMessages() []createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage {
	return v.Messages
}

// GetResult returns createEnvironmentCreateEnvironmentEnvironmentPayload.Result, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayload) GetResult() createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment {
	return v.Result
}

// createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage struct {
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
	// A unique error code for the type of validation used.
	Code string `json:"code"`
}

// GetField returns createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// GetCode returns createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment includes the requested fields of the GraphQL type Environment.
// The GraphQL type's documentation follows.
//
// An environment within a project (full type with relations).
type createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment.Id, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment) GetId() string {
	return v.Id
}

// GetName returns createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment.Name, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment) GetName() string {
	return v.Name
}

// GetDescription returns createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment.Description, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment.CreatedAt, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment.UpdatedAt, and is useful for accessing the field via an interface.
func (v *createEnvironmentCreateEnvironmentEnvironmentPayloadResultEnvironment) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// createEnvironmentResponse is returned by createEnvironment on success.
type createEnvironmentResponse struct {
	// Create a new environment in a project.
	CreateEnvironment createEnvironmentCreateEnvironmentEnvironmentPayload `json:"createEnvironment"`
}

// GetCreateEnvironment returns createEnvironmentResponse.CreateEnvironment, and is useful for accessing the field via an interface.
func (v *createEnvironmentResponse) GetCreateEnvironment() createEnvironmentCreateEnvironmentEnvironmentPayload {
	return v.CreateEnvironment
}

// createProjectCreateProjectProjectPayload includes the requested fields of the GraphQL type ProjectPayload.
type createProjectCreateProjectProjectPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []createProjectCreateProjectProjectPayloadMessagesValidationMessage `json:"messages"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result createProjectCreateProjectProjectPayloadResultProject `json:"result"`
}

// GetSuccessful returns createProjectCreateProjectProjectPayload.Successful, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns createProjectCreateProjectProjectPayload.Messages, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayload) GetMessages() []createProjectCreateProjectProjectPayloadMessagesValidationMessage {
	return v.Messages
}

// GetResult returns createProjectCreateProjectProjectPayload.Result, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayload) GetResult() createProjectCreateProjectProjectPayloadResultProject {
	return v.Result
}

// createProjectCreateProjectProjectPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type createProjectCreateProjectProjectPayloadMessagesValidationMessage struct {
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
	// A unique error code for the type of validation used.
	Code string `json:"code"`
}

// GetField returns createProjectCreateProjectProjectPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns createProjectCreateProjectProjectPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// GetCode returns createProjectCreateProjectProjectPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// createProjectCreateProjectProjectPayloadResultProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (full type with relations).
type createProjectCreateProjectProjectPayloadResultProject struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns createProjectCreateProjectProjectPayloadResultProject.Id, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetId() string { return v.Id }

// GetName returns createProjectCreateProjectProjectPayloadResultProject.Name, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetName() string { return v.Name }

// GetDescription returns createProjectCreateProjectProjectPayloadResultProject.Description, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns createProjectCreateProjectProjectPayloadResultProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns createProjectCreateProjectProjectPayloadResultProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *createProjectCreateProjectProjectPayloadResultProject) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// createProjectResponse is returned by createProject on success.
type createProjectResponse struct {
	// Create a new project.
	CreateProject createProjectCreateProjectProjectPayload `json:"createProject"`
}

// GetCreateProject returns createProjectResponse.CreateProject, and is useful for accessing the field via an interface.
func (v *createProjectResponse) GetCreateProject() createProjectCreateProjectProjectPayload {
	return v.CreateProject
}

// deleteEnvironmentDeleteEnvironmentEnvironmentPayload includes the requested fields of the GraphQL type EnvironmentPayload.
type deleteEnvironmentDeleteEnvironmentEnvironmentPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage `json:"messages"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment `json:"result"`
}

// GetSuccessful returns deleteEnvironmentDeleteEnvironmentEnvironmentPayload.Successful, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns deleteEnvironmentDeleteEnvironmentEnvironmentPayload.Messages, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayload) GetMessages() []deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage {
	return v.Messages
}

// GetResult returns deleteEnvironmentDeleteEnvironmentEnvironmentPayload.Result, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayload) GetResult() deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment {
	return v.Result
}

// deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage struct {
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
	// A unique error code for the type of validation used.
	Code string `json:"code"`
}

// GetField returns deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// GetCode returns deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment includes the requested fields of the GraphQL type Environment.
// The GraphQL type's documentation follows.
//
// An environment within a project (full type with relations).
type deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment struct {
	Id string `json:"id"`
	// Human-readable name
	Name string `json:"name"`
}

// GetId returns deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment.Id, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment) GetId() string {
	return v.Id
}

// GetName returns deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment.Name, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentDeleteEnvironmentEnvironmentPayloadResultEnvironment) GetName() string {
	return v.Name
}

// deleteEnvironmentResponse is returned by deleteEnvironment on success.
type deleteEnvironmentResponse struct {
	// Delete an environment. All packages must be decommissioned before deletion.
	DeleteEnvironment deleteEnvironmentDeleteEnvironmentEnvironmentPayload `json:"deleteEnvironment"`
}

// GetDeleteEnvironment returns deleteEnvironmentResponse.DeleteEnvironment, and is useful for accessing the field via an interface.
func (v *deleteEnvironmentResponse) GetDeleteEnvironment() deleteEnvironmentDeleteEnvironmentEnvironmentPayload {
	return v.DeleteEnvironment
}

// deleteProjectDeleteProjectProjectPayload includes the requested fields of the GraphQL type ProjectPayload.
type deleteProjectDeleteProjectProjectPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage `json:"messages"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result deleteProjectDeleteProjectProjectPayloadResultProject `json:"result"`
}

// GetSuccessful returns deleteProjectDeleteProjectProjectPayload.Successful, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns deleteProjectDeleteProjectProjectPayload.Messages, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayload) GetMessages() []deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage {
	return v.Messages
}

// GetResult returns deleteProjectDeleteProjectProjectPayload.Result, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayload) GetResult() deleteProjectDeleteProjectProjectPayloadResultProject {
	return v.Result
}

// deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage struct {
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
	// A unique error code for the type of validation used.
	Code string `json:"code"`
}

// GetField returns deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// GetCode returns deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// deleteProjectDeleteProjectProjectPayloadResultProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (full type with relations).
type deleteProjectDeleteProjectProjectPayloadResultProject struct {
	Id string `json:"id"`
	// Human-readable name
	Name string `json:"name"`
}

// GetId returns deleteProjectDeleteProjectProjectPayloadResultProject.Id, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadResultProject) GetId() string { return v.Id }

// GetName returns deleteProjectDeleteProjectProjectPayloadResultProject.Name, and is useful for accessing the field via an interface.
func (v *deleteProjectDeleteProjectProjectPayloadResultProject) GetName() string { return v.Name }

// deleteProjectResponse is returned by deleteProject on success.
type deleteProjectResponse struct {
	// Delete a project. All environments must be empty before deletion.
	DeleteProject deleteProjectDeleteProjectProjectPayload `json:"deleteProject"`
}

// GetDeleteProject returns deleteProjectResponse.DeleteProject, and is useful for accessing the field via an interface.
func (v *deleteProjectResponse) GetDeleteProject() deleteProjectDeleteProjectProjectPayload {
	return v.DeleteProject
}

// getEnvironmentEnvironment includes the requested fields of the GraphQL type Environment.
// The GraphQL type's documentation follows.
//
// An environment within a project (full type with relations).
type getEnvironmentEnvironment struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	// The project this environment belongs to.
	Project getEnvironmentEnvironmentProject `json:"project"`
}

// GetId returns getEnvironmentEnvironment.Id, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironment) GetId() string { return v.Id }

// GetName returns getEnvironmentEnvironment.Name, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironment) GetName() string { return v.Name }

// GetDescription returns getEnvironmentEnvironment.Description, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironment) GetDescription() string { return v.Description }

// GetCreatedAt returns getEnvironmentEnvironment.CreatedAt, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironment) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns getEnvironmentEnvironment.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironment) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetProject returns getEnvironmentEnvironment.Project, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironment) GetProject() getEnvironmentEnvironmentProject { return v.Project }

// getEnvironmentEnvironmentProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (full type with relations).
type getEnvironmentEnvironmentProject struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns getEnvironmentEnvironmentProject.Id, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironmentProject) GetId() string { return v.Id }

// GetName returns getEnvironmentEnvironmentProject.Name, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironmentProject) GetName() string { return v.Name }

// GetDescription returns getEnvironmentEnvironmentProject.Description, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironmentProject) GetDescription() string { return v.Description }

// GetCreatedAt returns getEnvironmentEnvironmentProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironmentProject) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns getEnvironmentEnvironmentProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getEnvironmentEnvironmentProject) GetUpdatedAt() time.Time { return v.UpdatedAt }

// getEnvironmentResponse is returned by getEnvironment on success.
type getEnvironmentResponse struct {
	// Get an environment by ID (identifier).
	Environment getEnvironmentEnvironment `json:"environment"`
}

// GetEnvironment returns getEnvironmentResponse.Environment, and is useful for accessing the field via an interface.
func (v *getEnvironmentResponse) GetEnvironment() getEnvironmentEnvironment { return v.Environment }

// getProjectProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (full type with relations).
type getProjectProject struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	// Environments in this project (paginated).
	Environments getProjectProjectEnvironmentsEnvironmentsPage `json:"environments"`
}

// GetId returns getProjectProject.Id, and is useful for accessing the field via an interface.
func (v *getProjectProject) GetId() string { return v.Id }

// GetName returns getProjectProject.Name, and is useful for accessing the field via an interface.
func (v *getProjectProject) GetName() string { return v.Name }

// GetDescription returns getProjectProject.Description, and is useful for accessing the field via an interface.
func (v *getProjectProject) GetDescription() string { return v.Description }

// GetCreatedAt returns getProjectProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *getProjectProject) GetCreatedAt() time.Time { return v.CreatedAt }

// GetUpdatedAt returns getProjectProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getProjectProject) GetUpdatedAt() time.Time { return v.UpdatedAt }

// GetEnvironments returns getProjectProject.Environments, and is useful for accessing the field via an interface.
func (v *getProjectProject) GetEnvironments() getProjectProjectEnvironmentsEnvironmentsPage {
	return v.Environments
}

// getProjectProjectEnvironmentsEnvironmentsPage includes the requested fields of the GraphQL type EnvironmentsPage.
type getProjectProjectEnvironmentsEnvironmentsPage struct {
	// Pagination cursors
	Cursor getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor `json:"cursor"`
	// A list of type environment_leaf.
	Items []getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf `json:"items"`
}

// GetCursor returns getProjectProjectEnvironmentsEnvironmentsPage.Cursor, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPage) GetCursor() getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor {
	return v.Cursor
}

// GetItems returns getProjectProjectEnvironmentsEnvironmentsPage.Items, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPage) GetItems() []getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf {
	return v.Items
}

// getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor includes the requested fields of the GraphQL type PaginationCursor.
type getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor struct {
	// Cursor to the next page
	Next string `json:"next"`
	// Cursor to the previous page
	Previous string `json:"previous"`
}

// GetNext returns getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor.Next, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor) GetNext() string {
	return v.Next
}

// GetPrevious returns getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor.Previous, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageCursorPaginationCursor) GetPrevious() string {
	return v.Previous
}

// getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf includes the requested fields of the GraphQL type EnvironmentLeaf.
// The GraphQL type's documentation follows.
//
// An environment within a project (leaf type, no has_many relations).
type getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Id, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetId() string {
	return v.Id
}

// GetName returns getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Name, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetName() string {
	return v.Name
}

// GetDescription returns getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Description, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.CreatedAt, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.UpdatedAt, and is useful for accessing the field via an interface.
func (v *getProjectProjectEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// getProjectResponse is returned by getProject on success.
type getProjectResponse struct {
	// Get a project by ID.
	Project getProjectProject `json:"project"`
}

// GetProject returns getProjectResponse.Project, and is useful for accessing the field via an interface.
func (v *getProjectResponse) GetProject() getProjectProject { return v.Project }

// listEnvironmentsEnvironmentsEnvironmentsPage includes the requested fields of the GraphQL type EnvironmentsPage.
type listEnvironmentsEnvironmentsEnvironmentsPage struct {
	// Pagination cursors
	Cursor listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor `json:"cursor"`
	// A list of type environment_leaf.
	Items []listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf `json:"items"`
}

// GetCursor returns listEnvironmentsEnvironmentsEnvironmentsPage.Cursor, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPage) GetCursor() listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor {
	return v.Cursor
}

// GetItems returns listEnvironmentsEnvironmentsEnvironmentsPage.Items, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPage) GetItems() []listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf {
	return v.Items
}

// listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor includes the requested fields of the GraphQL type PaginationCursor.
type listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor struct {
	// Cursor to the next page
	Next string `json:"next"`
	// Cursor to the previous page
	Previous string `json:"previous"`
}

// GetNext returns listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor.Next, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor) GetNext() string {
	return v.Next
}

// GetPrevious returns listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor.Previous, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageCursorPaginationCursor) GetPrevious() string {
	return v.Previous
}

// listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf includes the requested fields of the GraphQL type EnvironmentLeaf.
// The GraphQL type's documentation follows.
//
// An environment within a project (leaf type, no has_many relations).
type listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	// The project this environment belongs to.
	Project listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf `json:"project"`
}

// GetId returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Id, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetId() string {
	return v.Id
}

// GetName returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Name, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetName() string {
	return v.Name
}

// GetDescription returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Description, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.CreatedAt, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// GetProject returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf.Project, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeaf) GetProject() listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf {
	return v.Project
}

// listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf includes the requested fields of the GraphQL type ProjectLeaf.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (leaf type, no has_many relations).
type listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf.Id, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf) GetId() string {
	return v.Id
}

// GetName returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf.Name, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf) GetName() string {
	return v.Name
}

// GetDescription returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf.Description, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf.CreatedAt, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listEnvironmentsEnvironmentsEnvironmentsPageItemsEnvironmentLeafProjectProjectLeaf) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// listEnvironmentsResponse is returned by listEnvironments on success.
type listEnvironmentsResponse struct {
	// List environments. Returns all environments visible to the user.
	Environments listEnvironmentsEnvironmentsEnvironmentsPage `json:"environments"`
}

// GetEnvironments returns listEnvironmentsResponse.Environments, and is useful for accessing the field via an interface.
func (v *listEnvironmentsResponse) GetEnvironments() listEnvironmentsEnvironmentsEnvironmentsPage {
	return v.Environments
}

// listProjectsProjectsProjectsPage includes the requested fields of the GraphQL type ProjectsPage.
type listProjectsProjectsProjectsPage struct {
	// Pagination cursors
	Cursor listProjectsProjectsProjectsPageCursorPaginationCursor `json:"cursor"`
	// A list of type project_leaf.
	Items []listProjectsProjectsProjectsPageItemsProjectLeaf `json:"items"`
}

// GetCursor returns listProjectsProjectsProjectsPage.Cursor, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPage) GetCursor() listProjectsProjectsProjectsPageCursorPaginationCursor {
	return v.Cursor
}

// GetItems returns listProjectsProjectsProjectsPage.Items, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPage) GetItems() []listProjectsProjectsProjectsPageItemsProjectLeaf {
	return v.Items
}

// listProjectsProjectsProjectsPageCursorPaginationCursor includes the requested fields of the GraphQL type PaginationCursor.
type listProjectsProjectsProjectsPageCursorPaginationCursor struct {
	// Cursor to the next page
	Next string `json:"next"`
	// Cursor to the previous page
	Previous string `json:"previous"`
}

// GetNext returns listProjectsProjectsProjectsPageCursorPaginationCursor.Next, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageCursorPaginationCursor) GetNext() string { return v.Next }

// GetPrevious returns listProjectsProjectsProjectsPageCursorPaginationCursor.Previous, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageCursorPaginationCursor) GetPrevious() string {
	return v.Previous
}

// listProjectsProjectsProjectsPageItemsProjectLeaf includes the requested fields of the GraphQL type ProjectLeaf.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (leaf type, no has_many relations).
type listProjectsProjectsProjectsPageItemsProjectLeaf struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns listProjectsProjectsProjectsPageItemsProjectLeaf.Id, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageItemsProjectLeaf) GetId() string { return v.Id }

// GetName returns listProjectsProjectsProjectsPageItemsProjectLeaf.Name, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageItemsProjectLeaf) GetName() string { return v.Name }

// GetDescription returns listProjectsProjectsProjectsPageItemsProjectLeaf.Description, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageItemsProjectLeaf) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns listProjectsProjectsProjectsPageItemsProjectLeaf.CreatedAt, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageItemsProjectLeaf) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns listProjectsProjectsProjectsPageItemsProjectLeaf.UpdatedAt, and is useful for accessing the field via an interface.
func (v *listProjectsProjectsProjectsPageItemsProjectLeaf) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// listProjectsResponse is returned by listProjects on success.
type listProjectsResponse struct {
	// List projects. Returns a paginated list sorted by name by default.
	Projects listProjectsProjectsProjectsPage `json:"projects"`
}

// GetProjects returns listProjectsResponse.Projects, and is useful for accessing the field via an interface.
func (v *listProjectsResponse) GetProjects() listProjectsProjectsProjectsPage { return v.Projects }

// updateEnvironmentResponse is returned by updateEnvironment on success.
type updateEnvironmentResponse struct {
	// Update an environment's name or description.
	UpdateEnvironment updateEnvironmentUpdateEnvironmentEnvironmentPayload `json:"updateEnvironment"`
}

// GetUpdateEnvironment returns updateEnvironmentResponse.UpdateEnvironment, and is useful for accessing the field via an interface.
func (v *updateEnvironmentResponse) GetUpdateEnvironment() updateEnvironmentUpdateEnvironmentEnvironmentPayload {
	return v.UpdateEnvironment
}

// updateEnvironmentUpdateEnvironmentEnvironmentPayload includes the requested fields of the GraphQL type EnvironmentPayload.
type updateEnvironmentUpdateEnvironmentEnvironmentPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage `json:"messages"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment `json:"result"`
}

// GetSuccessful returns updateEnvironmentUpdateEnvironmentEnvironmentPayload.Successful, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayload) GetSuccessful() bool {
	return v.Successful
}

// GetMessages returns updateEnvironmentUpdateEnvironmentEnvironmentPayload.Messages, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayload) GetMessages() []updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage {
	return v.Messages
}

// GetResult returns updateEnvironmentUpdateEnvironmentEnvironmentPayload.Result, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayload) GetResult() updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment {
	return v.Result
}

// updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage struct {
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
	// A unique error code for the type of validation used.
	Code string `json:"code"`
}

// GetField returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// GetCode returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment includes the requested fields of the GraphQL type Environment.
// The GraphQL type's documentation follows.
//
// An environment within a project (full type with relations).
type updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment.Id, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment) GetId() string {
	return v.Id
}

// GetName returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment.Name, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment) GetName() string {
	return v.Name
}

// GetDescription returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment.Description, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment.CreatedAt, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment.UpdatedAt, and is useful for accessing the field via an interface.
func (v *updateEnvironmentUpdateEnvironmentEnvironmentPayloadResultEnvironment) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// updateProjectResponse is returned by updateProject on success.
type updateProjectResponse struct {
	// Update a project's name or description.
	UpdateProject updateProjectUpdateProjectProjectPayload `json:"updateProject"`
}

// GetUpdateProject returns updateProjectResponse.UpdateProject, and is useful for accessing the field via an interface.
func (v *updateProjectResponse) GetUpdateProject() updateProjectUpdateProjectProjectPayload {
	return v.UpdateProject
}

// updateProjectUpdateProjectProjectPayload includes the requested fields of the GraphQL type ProjectPayload.
type updateProjectUpdateProjectProjectPayload struct {
	// Indicates if the mutation completed successfully or not.
	Successful bool `json:"successful"`
	// A list of failed validations. May be blank or null if mutation succeeded.
	Messages []updateProjectUpdateProjectProjectPayloadMessagesValidationMessage `json:"messages"`
	// The object created/updated/deleted by the mutation. May be null if mutation failed.
	Result updateProjectUpdateProjectProjectPayloadResultProject `json:"result"`
}

// GetSuccessful returns updateProjectUpdateProjectProjectPayload.Successful, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayload) GetSuccessful() bool { return v.Successful }

// GetMessages returns updateProjectUpdateProjectProjectPayload.Messages, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayload) GetMessages() []updateProjectUpdateProjectProjectPayloadMessagesValidationMessage {
	return v.Messages
}

// GetResult returns updateProjectUpdateProjectProjectPayload.Result, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayload) GetResult() updateProjectUpdateProjectProjectPayloadResultProject {
	return v.Result
}

// updateProjectUpdateProjectProjectPayloadMessagesValidationMessage includes the requested fields of the GraphQL type ValidationMessage.
// The GraphQL type's documentation follows.
//
// Validation messages are returned when mutation input does not meet the requirements.
// While client-side validation is highly recommended to provide the best User Experience,
// All inputs will always be validated server-side.
//
// Some examples of validations are:
//
// * Username must be at least 10 characters
// * Email field does not contain an email address
// * Birth Date is required
//
// While GraphQL has support for required values, mutation data fields are always
// set to optional in our API. This allows 'required field' messages
// to be returned in the same manner as other validations. The only exceptions
// are id fields, which may be required to perform updates or deletes.
type updateProjectUpdateProjectProjectPayloadMessagesValidationMessage struct {
	// The input field that the error applies to. The field can be used to
	// identify which field the error message should be displayed next to in the
	// presentation layer.
	//
	// If there are multiple errors to display for a field, multiple validation
	// messages will be in the result.
	//
	// This field may be null in cases where an error cannot be applied to a specific field.
	Field string `json:"field"`
	// A friendly error message, appropriate for display to the end user.
	//
	// The message is interpolated to include the appropriate variables.
	//
	// Example: `Username must be at least 10 characters`
	//
	// This message may change without notice, so we do not recommend you match against the text.
	// Instead, use the *code* field for matching.
	Message string `json:"message"`
	// A unique error code for the type of validation used.
	Code string `json:"code"`
}

// GetField returns updateProjectUpdateProjectProjectPayloadMessagesValidationMessage.Field, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadMessagesValidationMessage) GetField() string {
	return v.Field
}

// GetMessage returns updateProjectUpdateProjectProjectPayloadMessagesValidationMessage.Message, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadMessagesValidationMessage) GetMessage() string {
	return v.Message
}

// GetCode returns updateProjectUpdateProjectProjectPayloadMessagesValidationMessage.Code, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadMessagesValidationMessage) GetCode() string {
	return v.Code
}

// updateProjectUpdateProjectProjectPayloadResultProject includes the requested fields of the GraphQL type Project.
// The GraphQL type's documentation follows.
//
// A container for organizing environments and infrastructure (full type with relations).
type updateProjectUpdateProjectProjectPayloadResultProject struct {
	Id string `json:"id"`
	// Human-readable name
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// GetId returns updateProjectUpdateProjectProjectPayloadResultProject.Id, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetId() string { return v.Id }

// GetName returns updateProjectUpdateProjectProjectPayloadResultProject.Name, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetName() string { return v.Name }

// GetDescription returns updateProjectUpdateProjectProjectPayloadResultProject.Description, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetDescription() string {
	return v.Description
}

// GetCreatedAt returns updateProjectUpdateProjectProjectPayloadResultProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetCreatedAt() time.Time {
	return v.CreatedAt
}

// GetUpdatedAt returns updateProjectUpdateProjectProjectPayloadResultProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *updateProjectUpdateProjectProjectPayloadResultProject) GetUpdatedAt() time.Time {
	return v.UpdatedAt
}

// The mutation executed by createEnvironment.
const createEnvironment_Operation = `
mutation createEnvironment ($organization: ID!, $project: ID!, $input: CreateEnvironmentInput!) {
	createEnvironment(organization: $organization, project: $project, input: $input) {
		successful
		messages {
			field
			message
			code
		}
		result {
			id
			name
			description
			createdAt
			updatedAt
		}
	}
}
`

func createEnvironment(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	project string,
	input CreateEnvironmentInput,
) (data_ *createEnvironmentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createEnvironment",
		Query:  createEnvironment_Operation,
		Variables: &__createEnvironmentInput{
			Organization: organization,
			Project:      project,
			Input:        input,
		},
	}

	data_ = &createEnvironmentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by createProject.
const createProject_Operation = `
mutation createProject ($organization: ID!, $input: CreateProjectInput!) {
	createProject(organization: $organization, input: $input) {
		successful
		messages {
			field
			message
			code
		}
		result {
			id
			name
			description
			createdAt
			updatedAt
		}
	}
}
`

func createProject(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	input CreateProjectInput,
) (data_ *createProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "createProject",
		Query:  createProject_Operation,
		Variables: &__createProjectInput{
			Organization: organization,
			Input:        input,
		},
	}

	data_ = &createProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteEnvironment.
const deleteEnvironment_Operation = `
mutation deleteEnvironment ($organization: ID!, $id: ID!) {
	deleteEnvironment(organization: $organization, id: $id) {
		successful
		messages {
			field
			message
			code
		}
		result {
			id
			name
		}
	}
}
`

func deleteEnvironment(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	id string,
) (data_ *deleteEnvironmentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteEnvironment",
		Query:  deleteEnvironment_Operation,
		Variables: &__deleteEnvironmentInput{
			Organization: organization,
			Id:           id,
		},
	}

	data_ = &deleteEnvironmentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by deleteProject.
const deleteProject_Operation = `
mutation deleteProject ($organization: ID!, $id: ID!) {
	deleteProject(organization: $organization, id: $id) {
		successful
		messages {
			field
			message
			code
		}
		result {
			id
			name
		}
	}
}
`

func deleteProject(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	id string,
) (data_ *deleteProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "deleteProject",
		Query:  deleteProject_Operation,
		Variables: &__deleteProjectInput{
			Organization: organization,
			Id:           id,
		},
	}

	data_ = &deleteProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getEnvironment.
const getEnvironment_Operation = `
query getEnvironment ($organization: ID!, $id: ID!) {
	environment(organization: $organization, id: $id) {
		id
		name
		description
		createdAt
		updatedAt
		project {
			id
			name
			description
			createdAt
			updatedAt
		}
	}
}
`

func getEnvironment(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	id string,
) (data_ *getEnvironmentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getEnvironment",
		Query:  getEnvironment_Operation,
		Variables: &__getEnvironmentInput{
			Organization: organization,
			Id:           id,
		},
	}

	data_ = &getEnvironmentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by getProject.
const getProject_Operation = `
query getProject ($organization: ID!, $id: ID!) {
	project(organization: $organization, id: $id) {
		id
		name
		description
		createdAt
		updatedAt
		environments {
			cursor {
				next
				previous
			}
			items {
				id
				name
				description
				createdAt
				updatedAt
			}
		}
	}
}
`

func getProject(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	id string,
) (data_ *getProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "getProject",
		Query:  getProject_Operation,
		Variables: &__getProjectInput{
			Organization: organization,
			Id:           id,
		},
	}

	data_ = &getProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listEnvironments.
const listEnvironments_Operation = `
query listEnvironments ($organization: ID!, $filter: EnvironmentsFilter, $cursor: Cursor) {
	environments(organization: $organization, filter: $filter, cursor: $cursor) {
		cursor {
			next
			previous
		}
		items {
			id
			name
			description
			createdAt
			updatedAt
			project {
				id
				name
				description
				createdAt
				updatedAt
			}
		}
	}
}
`

func listEnvironments(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	filter EnvironmentsFilter,
	cursor scalars.Cursor,
) (data_ *listEnvironmentsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listEnvironments",
		Query:  listEnvironments_Operation,
		Variables: &__listEnvironmentsInput{
			Organization: organization,
			Filter:       filter,
			Cursor:       cursor,
		},
	}

	data_ = &listEnvironmentsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by listProjects.
const listProjects_Operation = `
query listProjects ($organization: ID!, $cursor: Cursor) {
	projects(organization: $organization, cursor: $cursor) {
		cursor {
			next
			previous
		}
		items {
			id
			name
			description
			createdAt
			updatedAt
		}
	}
}
`

func listProjects(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	cursor scalars.Cursor,
) (data_ *listProjectsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "listProjects",
		Query:  listProjects_Operation,
		Variables: &__listProjectsInput{
			Organization: organization,
			Cursor:       cursor,
		},
	}

	data_ = &listProjectsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by updateEnvironment.
const updateEnvironment_Operation = `
mutation updateEnvironment ($organization: ID!, $id: ID!, $input: UpdateEnvironmentInput!) {
	updateEnvironment(organization: $organization, id: $id, input: $input) {
		successful
		messages {
			field
			message
			code
		}
		result {
			id
			name
			description
			createdAt
			updatedAt
		}
	}
}
`

func updateEnvironment(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	id string,
	input UpdateEnvironmentInput,
) (data_ *updateEnvironmentResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "updateEnvironment",
		Query:  updateEnvironment_Operation,
		Variables: &__updateEnvironmentInput{
			Organization: organization,
			Id:           id,
			Input:        input,
		},
	}

	data_ = &updateEnvironmentResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by updateProject.
const updateProject_Operation = `
mutation updateProject ($organization: ID!, $id: ID!, $input: UpdateProjectInput!) {
	updateProject(organization: $organization, id: $id, input: $input) {
		successful
		messages {
			field
			message
			code
		}
		result {
			id
			name
			description
			createdAt
			updatedAt
		}
	}
}
`

func updateProject(
	ctx_ context.Context,
	client_ graphql.Client,
	organization string,
	id string,
	input UpdateProjectInput,
) (data_ *updateProjectResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "updateProject",
		Query:  updateProject_Operation,
		Variables: &__updateProjectInput{
			Organization: organization,
			Id:           id,
			Input:        input,
		},
	}

	data_ = &updateProjectResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
